module.exports = {
  siteTitle: 'JJUG CCC 2020 Spring',
  siteTitleAlt: 'JJUG CCC',
  siteLogo: '/icons/icon-512x512.png',
  siteUrl: 'https://ccc2020spring.java-users.jp/',
  pathPrefix: '',
  siteDescription: 'JJUG CCC 2020 Spring/Japan Java User Group Cross Community Conference 2020 Spring',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  disqusShortname: 'jjug-ccc-2020-spring',
  userName: 'JJUG',
  userTwitter: 'JJUG',
  userLocation: 'Tokyo',
  userDescription: 'Japan Java User Group',
  copyright: 'Copyright © 2007-2020 JJUG - All rights reserved.',
  themeColor: '#DB7093',
  backgroundColor: '#ffffff',
}
